# Generated by Django 3.0.5 on 2023-04-16 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
