# Generated by Django 3.0.5 on 2023-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20230416_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
