# Generated by Django 3.0.5 on 2023-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20230415_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='last_donated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
